account/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView,LoginView
from django.urls import path
from django.views.generic import CreateView
app_name = 'account'
urlpatterns = [
  path('signup/',CreateView.as_view(
    template_name='account/signup.html',
    form_class=UserCreationForm,
    success_url='/',),name = 'signup'),
path('login/',LoginView.as_view(
  redirect_authenticated_user=True,
  template_name='account/login.html'
),name='login' ),
path('account/logout/',LogoutView.as_view(),name='logout'),

]

smapro2022/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tech_marathon/', include('tech_marathon.urls')),
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
]

tech_marathon/urls.py
from django.urls import path
from .views import top, user, book

app_name = 'tech_marathon'
urlpatterns = [
    path('', top.TopTemplateView.index, name='top'),

    path('my_page/', user.UserTemplateView.my_page, name='my_page'),
    path('my_page/edit/', user.UserTemplateView.edit, name='my_page_edit'),
    path('other_users/', user.UserTemplateView.other_users, name='other_users'),
    path('other_user/<int:user_id>/', user.UserTemplateView.other_user, name='other_user'),

    path('book/<int:book_id>', book.BookTemplateView.show, name='book_show'),
    path('book/new', book.BookTemplateView.new, name='book_new'),
    path('book/create', book.BookTemplateView.create, name='book_create'),
    path('book/edit/<int:book_id>', book.BookTemplateView.edit, name='book_edit'),
    path('book/delete', book.BookTemplateView.delete, name='book_delete'),
    path('book/unread_books', book.BookTemplateView.unread_books, name='unread_books'),
]

account/models.py
from django.db import models

# Create your models here.

tech_marathon/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
  name = models.CharField(max_length=20)

class Book(models.Model):
  title = models.CharField(max_length=50)
  memo = models.CharField(max_length=200, null=True)
  read_status = models.BooleanField(default=False)
  begin_date = models.DateTimeField('purchased date')
  end_date = models.DateTimeField('finished reading date', null=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  category = models.ManyToManyField(Category, related_name='book', null=True)

account/forms.py
from django import forms

class AccountForm(forms.Form):
  name = forms.CharField(label="名前")
  password = forms.CharField(label="パスワード", widget=forms.PasswordInput(), min_length=8)

tech_marathon/forms.py
from django import forms

class BookForm(forms.Form):
  title = forms.CharField(label="タイトル")
  memo = forms.CharField(label="メモ")
  read_status = forms.BooleanField(label="よんだか")
  begin_date = forms.DateField(label="購入日", widget=forms.SelectDateWidget())
  end_date = forms.DateField(label="読破日", widget=forms.SelectDateWidget())
  category = forms.CharField(label="カテゴリー")

class SignInForm(forms.Form):
  name = forms.CharField(label="名前")
  password = forms.CharField(label="パスワード", widget=forms.PasswordInput(), min_length=8)

class SignUpForm(forms.Form):
  name = forms.CharField(label="名前")
  email = forms.CharField(label="メールアドレス")
  password = forms.CharField(label="パスワード", widget=forms.PasswordInput(), min_length=8)

account/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from account.forms import AccountForm

class AcountTemplateForm(TemplateView):
  def login(request):
    ctx = {
      "form": AccountForm()
    }
    return render(request, 'account/login.html', ctx)

smapro2022/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View

class index(View):
    def get(self, request, *args, **kwargs):
        return redirect(reverse('tech_marathon:top'))
index = index.as_view()

tech_marathon/views/book.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, reverse
from tech_marathon.models import Book
from tech_marathon.forms import BookForm
from django.contrib.auth.models import User

class BookTemplateView(TemplateView):

  # 　詳細ページ
  def show(request, book_id):
    ctx = {
      "book": Book.objects.prefetch_related('category').get(id=book_id)
    }
    return render(request, 'tech_marathon/book/show.html', ctx)

  # 作成フォーム
  # TODO
  def new(request):
    ctx = {
      "form": BookForm()
    }
    return render(request, 'tech_marathon/book/new.html', ctx)

  # 登録
  # TODO
  def create(request):
    form = BookForm(request.POST)
    form.save(user_id=1)
    return redirect(request, 'tech_marathon/user/top.html')

  # 編集
  # TODO
  def edit(request, book_id):
    ctx = {
      "form": BookForm(),
      "book": Book.objects.filter(id=book_id)
    }
    return render(request, 'tech_marathon/book/edit.html', ctx)

  # 削除
  # TODO
  def delete(request):
    return redirect(request, 'tech_marathon/top.html')

  # 未読本を一覧表示
  def unread_books(request):
    ctx = {
      # TODO
      "books": Book.objects.filter(user_id=request.user.id, read_status=False)
    }
    return render(request, 'tech_marathon/book/unread_books.html', ctx)

tech_marathon/views/top.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, reverse
from tech_marathon.models import Book
from django.contrib.auth.models import User

class TopTemplateView(TemplateView):

  # トップページ
  def index(request):
    ctx = {
      'user': User.objects.get(id=request.user.id),
      'books': Book.objects.prefetch_related('category').filter(user_id=request.user.id, read_status=True)
    }
    return render(request, 'tech_marathon/top.html', ctx)

tech_marathon/views/user.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, reverse
from tech_marathon.models import Book
from tech_marathon.forms import SignInForm, SignUpForm
from django.db import models
from django.contrib.auth.models import User
class UserTemplateView(TemplateView):

  # ログインしているユーザのマイページ
  def my_page(request):
    ctx = {
      "user": User.objects.get(id=request.user.id)
    }
    return render(request, 'tech_marathon/user/my_page.html', ctx)

  # マイページ情報を編集
  # TODO
  def edit(request):
    return render(request, 'tech_marathon/user/edit.html')

  # 他のユーザーたち
  def other_users(request):
    ctx = {
      # TODO
      "other_users": User.object.exclude(id=request.user.id, read_status=True)
    }
    return render(request,'tech_marathon/user/other_users.html', ctx)

  # 他のユーザーの詳細ページ
  def other_user(request, user_id):
    ctx = {
      "user": User.objects.get(id=request.user.id),
      "books": Book.object.filter(user_id=user_id, read_status=True)
    }
    return render(request,'tech_marathon/user/other_user.html', ctx)

tech_marathon/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TechMarathon</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"       rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
  <header>
    {% include "header.html" %}
  </header>

  <div>
    <a href="{% url 'account:signup' %}">ログインへ</a>
    <a href="{% url 'account:login' %}">サインアップへ</a>
    <a href="{% url 'tech_marathon:my_page' %}">マイページへ</a>
    <a href="{% url 'tech_marathon:my_page_edit' %}">マイページ編集ページへ</a>
    <a href="{% url 'tech_marathon:other_users' %}">他のユーザの一覧ページへ</a>
    <a href="{% url 'tech_marathon:other_user' 1 %}">他のユーザの詳細ページへ</a>
    <a href="{% url 'tech_marathon:book_show' 1 %}">本の詳細ページへ</a>
    <a href="{% url 'tech_marathon:book_new' %}">本の登録ページへ</a>
    <a href="{% url 'tech_marathon:book_edit' 1 %}">本の編集ページへ</a>
    <a href="{% url 'tech_marathon:unread_books' %}">未読本一覧ページへ</a>
    <ul class="nabra-nav mr-md2">
      {% if user.is_authenticated %}
      <li class="nav-item"><a class="navlink" href="{% url 'account:logout' %}">ログアウト</a></li>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">ログイン</a></li>
      {% endif %}
    </ul>
  </div>

  <p>----base---</p>

  <div>
    {% block contents %}
    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

tech_marathon/templates/header.html
{% load static %}
<!-- <div>
    <h1>header</h1>
</div> -->

<nav class="navbar navbar-light bg-light">
    <div class="container-fluid" style="  background: linear-gradient(-135deg,#fd9c18, #ff5726);">
      <a class="navbar-brand" href="#">
        <img src="/static/images/無題73_20221211143321-removebg-preview.png" alt="" width="100%" height="60">
      </a>
    </div>
  </nav>

tech_marathon/templates/tech_marathon/book/edit.html
{% extends 'base.html' %}
{% block contents %}
{% load widget_tweaks %}

<div>
    <h1>/book/edit/{{ book_id }}</h1>
</div>

{% endblock %}

tech_marathon/templates/tech_marathon/book/new.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}
{% load widget_tweaks %}

<link rel="stylesheet" href="{% static 'css/book/new.css' %}">

<body>
    <div class="wrapper">
        <header class="header">
            <h1 class="logo">技術書を登録しよう！</h1>
        </header>
        <form method="POST" action="{% url 'tech_marathon:book_create' %}">
            {% csrf_token %}

            <span class="">書籍名：</span>
            {{ form.title | add_class:""}}
            <span class="">分野または言語名：</span>
            {{ form.category | add_class:""}}
            <span class="">購入日：</span>
            {{ form.begin_date | add_class:""}}
            <span class="">読了日：</span>
            {{ form.end_date | add_class:""}}
            <span class="">メモ：</span>
            {{ form.memo | add_class:""}}
            <!-- <span class="">画像をアップロード：</span> -->
            <!-- {{ form.memo | add_class:""}} -->

            <button type="submit" class="btn btn-ptrimary">登録</button>
        </form>

            <!-- <table border="0">
                <tr>
                    <td align="right"><b> 書籍名：</b></td>
                    <td><input type="text" name="name" size="30" maxlength="20"></td>
                </tr>
                <tr>
                    <td align="right"><b> 分野または言語名：</b></td>
                    <td><input type="text" name="name" size="30" maxlength="20"></td>
                </tr>
                <tr>
                    <td align="right"><b> 購入日：</b></td>
                    <td><input type="data" name="name" ></td>
                </tr>
                <tr>
                    <td align="right"><b> 読了日：</b></td>
                    <td><input type="data" name="name" ></td>
                </tr>
                <tr>
                    <td align="right"><b> メモ：</b></td>
                    <td><input type="text" name="memo" size="50" maxlength="50"></td>
                </tr>
                <tr>
                    <td align="right"><b> 画像をアップロード：</b></td>
                    <td><input type="file" name="photo" ></td><br>
                </tr>
                <tr>
                    <td></td>
                    <td>
                      <input type="reset" value="リセット">
                      <input type="submit" value="送信">
                    </td>
                </tr>


    </div>
</body>

{% endblock %}

tech_marathon/templates/tech_marathon/book/show.html
{% extends 'base.html' %}
{% block contents %}

<div>
    <h1>/book/{{ book.id }}</h1>
</div>

<p>{{ book.title }}</p>
<p>{{ book.memo }}</p>
<p>{{ book.begin_date }}</p>
<p>{{ book.end_date }}</p>

<a href="{% url 'tech_marathon:book_edit' book.id " class="btn">編集する</a>
<a href="{% url 'tech_marathon:book_delete'" action="delete" class="btn">削除する</a>
{% endblock %}

tech_marathon/templates/tech_marathon/book/unread_books.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/unread_books.css' %}">

<div>
    <h1>未読本一覧</h1>
</div>

<div class="container">
    <div class="row">
      <div class="col">
        <img class="my-5 w-100" src="/static/images/n.jpg">
      </div>
      <div class="col d-flex align-items-center">
        <p class="mb-0">ブロックチェーン・プログラミング</p>
      </div>
    </div>
</div>

<div class="container">
    <div class="row">
      <div class="col">
        <img class="my-5 w-100" src="/static/images/o.jpg">
      </div>
      <div class="col d-flex align-items-center">
        <p class="mb-0">ゼロから始まるPython機械学習</p>
      </div>
    </div>
</div>

<div class="container">
    <div class="row">
      <div class="col">
        <img class="my-5 w-100" src="/static/images/p.jpg">
      </div>
      <div class="col d-flex align-items-center">
        <p class="mb-0">Rustプログラミング入門</p>
      </div>
    </div>
</div>
{% endblock %}

tech_marathon/templates/tech_marathon/top.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/top.css' %}">

<meta charset="UTF-8">
<title>tech_marathon</title>
<div class="bg_test" >

    <header class="header" >
        <h1 class="logo">○○さんのコース</h1>
        <h2 class="number">読んだ冊数12冊</h2>
    </header>
    <div class="grid">
        <div class="card">
            <img src="/static/images/a.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/b.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/c.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/d.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/e.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/f.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/g.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/h.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/i.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/j.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/k.jpg" height="150px" alt="" />
        </div>
        <div class="card">
            <img src="/static/images/l.jpg" height="150px" alt="" />
        </div>
    </div>

<p>{{ books }}</p>

<link rel="stylesheet" href="{% static 'css/top.css' %}">

<div class="bg_test">

    <!--ヘッダー-->
    <div class="header">
        <h1 class="logo">{{ user.name }}さんのコース</h1>
        <h2 class="number">読んだ冊数</h2>
        <img src="stick-man-g87887191f_1280.png" width="100" alt="">
    </div>
    <!--ヘッダー　ここまで-->
    <!--メイン-->
    <!-- <div> -->
        <ul>
            <li>
                <image href="画像パス">
                <p>{{ book.title }}</p>
            </li>
            <li>
                <image href="画像パス">
                <p>{{ book.title }}</p>
            </li>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
        </ul>
        <ul>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
            <li>
                <image href="画像パス">
                <p>タイトル</p>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

tech_marathon/templates/tech_marathon/top_page.html
{% extends 'base.html' %}
{% block contents %}

<div>
    <h1>トップページ</h1>
</div>

<div>
    <h4>ここにコンテンツを記述する</h4>
</div>

{% endblock %}

tech_marathon/templates/tech_marathon/user/edit.html
{% extends 'base.html' %}
{% block contents %}
{% load widget_tweaks %}

<div>
    <h1>/my_page/edit   edit</h1>
</div>


{% endblock %}

tech_marathon/templates/tech_marathon/user/my_page.html
{% extends 'base.html' %}
{% block contents %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/user/my_page.css' %}">

<!-- <div>
    <h1>/my_page   my_page</h1>
</div> -->

<!-- <p>{{ user.name }}</p>
<p>{{ user.goal }}</p> -->

<h1 style="text-align: center;">マイページ</h1><br>
    
<div class="container overflow-hidden">
    <div class="row gx-5 mb-4">
      <div class="col">
       <div class="p-3 border bg-light">ユーザー名</div>
      </div>
      <div class="col">
        <div class="p-3 border bg-light">{{ user.username }}</div>
      </div>
    </div>
    <div class="row gx-5 mb-4">
        <div class="col">
         <div class="p-3 border bg-light">目標</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">{{ user.goal }}</div>
        </div>
    </div>
    <div class="row gx-5 mb-4">
        <div class="col">
            <div class="p-3 border bg-light">読了本の総数</div>
        </div>
        <div class="col">
            <div class="p-3 border bg-light">16冊</div>
        </div>
    </div>
    <div class="row gx-5 mb-4">
        <div class="col">
         <div class="p-3 border bg-light">未読本の総数</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">４冊</div>
        </div>
    </div>
    
  
{% endblock %}

tech_marathon/templates/tech_marathon/user/other_user.html
{% extends 'base.html' %}
{% block contents %}

<div>
    <h1>/other_user/{{ user_id }}   other_user</h1>
</div>

<p>{{ books }}</p>

{% endblock %}

tech_marathon/templates/tech_marathon/user/other_users.html
{% extends 'base.html' %}
{% block contents %}

<!-- <div>
    <h1>/other_users   other_users</h1>
</div> -->

{% for user in other_users %}
    <p>{{ user.username }}</p>
    <p>{{ user.goal }}</p>
    <p>{{ user.books.count }}</p>
{% endfor %}
{% endblock %}

tech_marathon/templates/tech_marathon/user/sign_in.html
{% extends 'base.html' %}
{% block contents %}

<div>
    <h1>/user/sign_in   sign_in</h1>
</div>

<p>{{ form.as_p }}</p>



<link rel="stylesheet" href="{% static 'css/user/sign_in.css' %}">
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>tech_marathon</title>
    <link rel="stylesheet" href="css/sign_in.css">
</head>
<body>
    <div class="wrapper">
        <!--ヘッダー-->
        <header class="header">
            <h1 class="logo"  style="text-align:center" >ログイン</h1>
        </header>
        <!--ヘッダー　ここまで-->
        <!--メインここから-->
        <form action="cgi-bin/aaa.cgi" method="post">
            <table border="0">
                <tr>
                    <td align="right"><b> ユーザー名：</b></td>
                    <td><input type="text" name="name" size="30" maxlength="20"></td>
                </tr>
                <tr>
                    <td align="right"><b> パスワード：</b></td>
                    <td><input type="password" name="pass" size="6" maxlength="4"></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                      <input type="reset" value="リセット">
                      <input type="submit" value="送信">
                    </td>
                </tr>
            </table>
        </form>
        <!--メインここまで-->
        <!--フッター-->
        <footer class="footer">
            <li style="text-align:center"><a href="http://127.0.0.1:8000/tech_marathon/sign_up/">＊ユーザー登録はこちら</a></li>
        </footer>
        <!--フッター　ここまで-->
    </div>
</body>

{% endblock %}

tech_marathon/templates/tech_marathon/user/sign_up.html
{% extends 'base.html' %}
{% block contents %}

<div>
    <h1>/user/sign_up   sign_up</h1>
</div>

<p>{{ form.as_p }}</p>

<link rel="stylesheet" href="{% static 'css/user/sign_up.css' %}">
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>tech_marathon</title>
    <link rel="stylesheet" href="css/sign_up.css">
</head>
<body>
    <div class="wrapper">
        <!--ヘッダー-->
        <header class="header">
            <h1 class="logo"  style="text-align:center" >ユーザー登録</h1>
        </header>
        <!--ヘッダー　ここまで-->
        <!--メインここから-->
        <form action="cgi-bin/aaa.cgi" method="post">
            <table border="0">
                <tr>
                    <td align="right"><b> ユーザー名：</b></td>
                    <td><input type="text" name="name" size="30" maxlength="20"></td>
                </tr>
                <tr>
                    <td align="right"><b> パスワード：</b></td>
                    <td><input type="password" name="pass" size="6" maxlength="4"></td>
                </tr>
                <tr>
                    <td align="right"><b> パスワード確認：</b></td>
                    <td><input type="password" name="confirm" size="6" maxlength="4"></td>
                    <td><imput type="submit" value="送信"></imput></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                      <input type="reset" value="リセット">
                      <input type="submit" value="送信">
                    </td>
                </tr>
            </table>
        </form>
        <script>
            function CheckPassword(confirm){
                var input1 = password.value;
                var input2 = confirm.value;
                if (input1 != input2){
                    confirm.setCustomValidity("入力値が一致しません");
                } else{
                    confirm.setCustomValidity('');
                }
            }
        </script>
        <!--メインここまで-->
    </div>
</body>

{% endblock %}